### ISSUE TITLE
китайское реле.

### ISSUE THREAD

**Issue by bdu1977** [Araris/VersatileTimer#1]
добрый день. меня очень заинтересовал данный проект. хотел спросить, ваш проект можно исполнить на китайской плате с 2 реле и esp8622? [ссылка](https://aliexpress.ru/item/1005003516399175.html?gps-id=pcStoreJustForYou&item_id=1005003516399175&pdp_ext_f=%7B%22sku_id%22%3A%2212000026140417177%22%2C%22ship_from%22%3A%22%22%7D&pvid=4e72e72e-15c2-457b-8019-c9d8de4aafdd&scm=1007.23125.137358.0&scm-url=1007.23125.137358.0&scm_id=1007.23125.137358.0&sku_id=12000026140417177&spm=a2g0o.store_pc_home.smartJustForYou_81164640.0)
нужно что-то переделывать в скетче? где меняются pin для управления реле?
можно как-то связаться с вами?

**Comment by Araris** [comment]
Добрый день, я посмотрел описание модуля, проблем в его использовании для таймера не вижу. В скетче ничего переделывать не понадобится. Управляющие пины выбираются в WEB-интерфейсе таймера и на плате модуля.
**Но :** 
1. Я не любитель продуктов от WAVGAT, имел определённые с ними проблемы, больше не покупаю. Впрочем, это моё скромное мнение.
2. Для заливки прошивки в ESP8266 потребуется отдельный переходник USB-UART (в описании - "TTL serial port module").
3. Выбор управляющих пинов на модуле выполняется перемычками (или проводами), судя по "GPIO port introduction" в описании.
Заданные Вами вопросы наводят на мысль, что **самостоятельно** с пунктами 2 и 3 (возможно, и не только с ними) разобраться будет Вам нелегко. Впрочем, и это тоже моё скромное мнение ))))), но слово "самостоятельно" выделено не случайно.

**Comment by bdu1977** [comment]
под данный проект были закуплены платы с реле двух видов,
[вариант 1](https://www.aliexpress.com/snapshot/0.html?orderId=5016815693925308)
[вариант 2](https://www.aliexpress.com/snapshot/0.html?spm=a2g39.orderdetails.order_info.4.6b304aa6QxrOSk&orderId=5016861460225308&productId=32901222553&_ga=2.149649846.1633186257.1654082990-2029453817.1649409477) ,
а так же wemos D1 mini, но потом попалась на глаза плата от WAVGAT и я подумал, что ее удобнее будет использовать, поскольку она в сборе. 
буду пробовать сделать на всем что есть.
небольшое бы пожелание к данной прошивке, раз вы ее обновляете, то неплохо было бы встроить в прошивку обновление по ОТА, такое возможно  доделать?

**Comment by Araris** [comment]
Ссылки на заказы плат с реле двух видов я, естественно, открыть не могу, поскольку это не мои заказы.
В WEB-интерфейсе уже есть обновление прошивки.

**Comment by Araris** [comment]
Ну и неплохо удалить одну из библиотек
C:\Users\regis\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.7.4\libraries\LittleFS
C:\Program Files (x86)\Arduino\libraries\LittleFS
,проверив на соответствие той, что на https://github.com/esp8266/Arduino/tree/master/libraries/LittleFS

**Comment by bdu1977** [comment]
все работает, нужно было только ядро esp обновить до 3.0.2. это я уже понял , поэтому и удалил сообщение. на данный момент все работает, но у меня три вопроса по работе таймера есть.
1. при первом включении через точку доступа (192,168,4,1) , я в настройках выбираю свою сеть, ввожу пароль. ниже два переключателя, автоматитически получать IP , я выбираю данный пункт и при сохранении выходит ошибка, что поля ниже не заполонены (это шлюз, маска, IP) это так и должно быть, в любом случае эти поля необходимо заполнять?
2. как мне настроить работу таймера с двумя каналами, что бы один канал включился в 18,00 и выключился в 18,30, второй канал включился в 18,30 и выключился в 19,00 и потом они поочередно включаются и выключаются с периодичностью 30 мин и оба канала выключатся в 24,00. можно просто задать период включения выключения в определенном временном диапазоне?
3.  тут скорее вопрос не к вам, но все же, может сталкивались, таймер не работает с [твердотельным реле](https://www.aliexpress.com/snapshot/0.html?orderId=5016815693925308) индикаторы на плате реле работают, включаются и выключаются, как и положено, но вот само реле один раз включилось и потом просто не переключается, хотя по управляющему индикатору на плате реле видно, что оно не работает, а контакты реле замкнуты. в чем причина, может вы рабтали с такими?
4. помогите пожалуйста.

**Comment by Araris** [comment]
1. Там был мелкий баг, спасибо за подсказку, исправил.
2. Увы, для меня "периодический таймер" и "недельный и/или суточный таймер" - понятия разные, поэтому "задать период включения выключения в определенном временном диапазоне" - такого функционала там нет, и вряд ли будет.
Впрочем, задача решается созданием множества заданий "включить в 18:00", "выключить в 18:30", "включить в 19:00", "выключить в 19:30", и так до 24-х часов (точнее, до 00:00).
3. Это скорее проблемы с реле. Узнать, какое используется реле, я не могу, опять ссылка не на товар, а на заказ ((. Залейте в контроллер простейший Blink, согласовав управляющий пин с платой реле, и посмотрите, будет ли реле корректно отрабатывать переключения.

**Comment by bdu1977** [comment]
[вот ссылка на реле](https://aliexpress.ru/item/10000000648538.html?spm=a2g2w.productlist.0.0.42c459fcmO4sUq&sku_id=20000000002572741)

что касается Blink, то пробовал, реле один раз сразу включилось, а светодиод подклченный к реле горит постоянно, хотя светодиод на плате моргает.

буду пробовать еще, не так часто есть возможность заниматься пайкой, так что это может немного затянуться.

**Comment by Araris** [comment]
Попробуйте вместо светодиода подключить к реле нагрузку посерьёзнее, например, лампу накаливания. Тестером напряжение поизмеряйте - будете удивлены.
G3MB-202P, да и все прочие твердотельные реле не "закрываются" полностью, поэтому для свечения светодиода тока будет достаточно и при открытом, и при закрытом реле.

**Comment by bdu1977** [comment]
да, результатом я удивлен, с большой нагрузкой твердотелка работает на ура. но я о другом, плата которая была в первом посте с уже установленным модулем esp8266? отлично себя показала в работе при тестовом прогоне. надеюсь, что она будет работать и долгое время. за данный скетч огромное спасибо. думаю что теперь, мои гирлянды будут работать четко и лучше чем с механическим реле.
я скачал обновленный скетч, но автоматический выбор IP при первой настройке идет так же с ошибкой. переключатель стоит "автоматический выбор", но при нажатии сохранить, выскакивает ошибка - нужно заполнить все адреса и шлюзы для ручного выбора. не критично, но......

**Comment by Araris** [comment]
1. Что ж, если разобрались с платой из первого поста, значит я Ваш уровень недооценил, респект.
2. "но при нажатии сохранить, выскакивает ошибка" - да, что-то я упустил... Спасибо, буду дальше разбираться.

**Comment by bdu1977** [comment]
готовая плата с разным количество реле и уже установленным esp8266 на борту, просто создана для вашего скетча, ну или наоборот., готовое решение все же лучше чем то что нужно собирать. единственный минус данной платы, это нет usb разъема, тут нужен программатор и понимание как прошить esp а так все работает. до нового года есть время, все собрать в одну коробку, все запрограммировать и прочее. буду потихоньку разбираться с твердотелкой. в интернете пишут, что у них у всех есть ток утечки, и что в принципе от него не избавиться - ну если только полностью отключать, так что буду ковырять ее потихоньку.

что касается самого скетча и вебинтерфейса - есть пожелание, если оно конечно реализуемо. в данной версии на главной странице, сверху в шапке есть часы реального времени. но они к сожалению обновляются только при перезагрузке esp или самой страницы, было бы хорошо их динамическими сделать, что бы они реально ходили и показывали время независимо от перезагрузки.

**Comment by Araris** [comment]
WEB-интерфейс там сделан максимально просто, браузер запрашивает - esp8266 возвращает простейшую статическую HTML-страницу, поэтому о динамическом её обновлении пока говорить не приходится. Будет время и желание, может когда и переделаю, в планах есть.

**Comment by bdu1977** [comment]
есть еще парочка вопросов, с которыми у меня пока не ладится. это касается сохранение настроек и обновления. если я правильно понял, то:
1. сохранение настрое происходит в самой esp ? если нужно данный фай сохранить на компьютере, нужно нажать выгрузить. верно?
2. обновление, там два пункта, это сам скетч Firmware - его я могу спокойно получить из arduino ide с расширением bin , потом выбрать его на компьютере и обновиться. верно?
3. и пункт который мне не понятен, это FileSystem: - тут то же расширение bin и как сделать данный файл и чем он отличается от Firmware?

**Comment by Araris** [comment]
1. Почти в ESP, там возле неё чип с восемью ногами запаян. Верно, "Выгрузить" - сохранить на компьютер, "Загрузить" - загрузить с компьютера ранее сохранённый.
2. Верно, в IDE "Экспорт бинарного файла", затем в WEB-интерфейсе "Обновление прошивки"
3. Вопрос непонятен: FileSystem - что это, где это ?

**Comment by bdu1977** [comment]
при нажатии на кнопку обновить у меня появляется надпись обновить Firmware и две кнопки : выбрать файл и обновить, а ниже надпись обновить FileSystem  и ниже две кнопки: выбрать файл и обновить.

**Comment by Araris** [comment]
Теперь понятно, не сообразил сразу ((.
Диалог, вызываемый по кнопке "Обновление прошивки", выводит не мой скетч, а httpUpdater (см. файл ESP8266HTTPUpdateServer.h), запуская после выбора бинарного файла соответственно Update.begin(maxSketchSpace, U_FLASH), либо Update.begin(fsSize, U_FS), в исходниках всё написано.
Нижним рядом кнопок я не пользуюсь.

P.S. Интересно стало, нашёл https://esp8266.ru/forum/threads/esp8266httpupdateserver-zagruzka-fajlov.5432/
