### ISSUE TITLE
расширенный функционал таймера

### ISSUE THREAD

**Issue by bdu1977** [Araris/VersatileTimer#2]
собрал данный таймер. вещь просто шикарная. мне она идеально подходит для управления новогодними гирляндами и украшениями, которые попеременно будут меняться, что бы не наскучить.
но вот у меня возник вопрос, а вы сможете расширить данный функционал. смысл вот в чем (на примере новогодних украшений).  в разных комнатах, на елке, на улице или еще где-то висит 12 (максимальное число каналов) украшений, которые должны попеременно включаться, для каждого украшения нужен свой таймер делать или очень много проводов растаскивать от основного блока. а если попробовать сделать следующее на основе bluetooth или wi fi. имеется один основной модуль на основе wemos и  bluetooth или wi fi приемопередатчик - данный модуль можно разместить где угодно. а каждое украшение уже подключено через bluetooth или wi fi приемо-передатчик и реле, которое размещается там где нужно. и получается, что все управление разными нагрузками идет по воздуху. 
как показала практика, китайские модули с реле отлично работают с данным таймером.

**Comment by Araris** [comment]
Насколько я понял, речь о замене проводного управления исполнительными устройствами на беспроводное, а не о функционале таймера.
На GPIO пины каналов таймера вместо реле можно повесить любое устройство, управляемое логическими уровнями, например, передатчик (Bluetooth, WiFi, RF, LoRa, неважно), 
который будет передавать текущее состояние пина приёмнику (приёмникам), 
которые будут включать-выключать реле.

**Comment by bdu1977** [comment]
а в скетче не придется вносить изменения? надо попробовать как-нибудь, возможно получиться. спасибо за подсказку.
