### ISSUE TITLE
При старте нет режима AP

### ISSUE THREAD

**Issue by voshodvoshod** [Araris/VersatileTimer#3]
Здравствуйте.Arduino IDE  1.8.19, ядро 3.0.2, платы ESP-01, ESP-01S. Скетч компилируется и загружается в контроллеры.Программирую через мост USB-UART для этих плат с перемычкой gpio0-gnd.После снятия перемычки и перезагрузки в эфире нет никаких AP, как и при подключении плат с контроллерами в плату с реле. Сами ESP-01 исправны, т.к. при загрузке в них пробного скетча AP появляется и есть возможность подключится в браузере  по адресу 192.168.4.1. Посоветуйте, что я делаю неправильно?

**Comment by Araris** [comment]
Здравствуйте.
После прошивки скетча и первой загрузки контроллера **АР сразу не должна появляться**, алгоритм прописан следующий : 
Вызывается функция begin_WiFi_STA(), которая в течение WIFICONNECTIONTRYPERIOD пытается подключиться к Wi-Fi точке, указанной в файле Secrets.h. 
WIFICONNECTIONTRYPERIOD объявлен как 600000UL msec, **это десять минут**.
Если через десять минут контроллер не подключится, то он перезагружает себя в режим АР.
В общем, либо править скетч под себя, либо ждать десять минут.

**Comment by voshodvoshod** [comment]
Спасибо за ответ! Получилось! Видимо я не понял смысл инструкции:"При загрузке в рабочем режиме, в случае невозможности подключиться к WiFi в течение тридцати секунд, устройство перезагружается в режим точки доступа. 
В режиме точки доступа, в случае отсутствия подключений к http://192.168.4.1,через 10 минут устройство перезагружается в рабочий режим.", т.е. я ждал 30 сек., думая, что в это время плата в режиме клиента и только после этого пытался найти АР  в течении 10 мин.  Конечно плата оставалась подключённой и после. Но режим АР потом пропадал и естественно я ничего не видел. Устройство понравилось, спасибо!

**Comment by Araris** [comment]
И Вам спасибо за подсказку, исправил неточность в описании - "тридцати секунд" на "десяти минут".
