### ISSUE TITLE
очистка программ

### ISSUE THREAD

**Issue by bdu1977** [Araris/VersatileTimer#5]
спасибо за данный проект. очень помогает с гирляндами на новый год. последнее время происходит очистка памяти контроллера. при обрыве связи с роутером по любой причине, таймер очищает память, т.е при заходе на страницу настроек я вижу, что таймер подключен к роутеру, но в нем нет никаких программ управления. перезагрузка таймера не помогает. приходится восстанавливать все вручную из файла с резервной копией настроек. раньше такого не было, прошивка и список программ остался с прошлого года.
так же замечено что в режиме точки доступа я могу зайти в настройки 1 раз из 10, говорит что не верный логин или пароль, но 1 раз-то меня все же пускает. грешу на слабый роутер, но кинетик вроде не слабый, 
подскажите куда думать?

**Comment by bdu1977** [comment]
а иногда происходит вот такая вещь. при заходе на страницу настроек, выдается не полная информация, а по значку перезагрузки страницы видно, что страница загружена полностью. каналов рабочих у меня 2 и на каждый канал по 15 заданий. а на картинке вон что показывает.
![1](https://github.com/Araris/VersatileTimer/assets/95622729/060f6169-c785-4d3a-aa54-1e9f323b5488)

**Comment by porese** [comment]
Тоже такое наблюдаю, обычно после ресета в течении некоторого времени. 
Насчет сброса настроек таймера, попробуйте полностью стереть флеш, при прошивке (средствами ардуины), только копии скиньте куда нибудь, затрет. У меня помогло.
