### ISSUE TITLE
GPIO 9

### ISSUE THREAD

**Issue by bdu1977** [Araris/VersatileTimer#6]
при использовании всех 12 каналов, возникла ошибка. в настройках указано не использовать GPIO 6, 7, 8, 11 и желательно GPIO 1 не использовать. следуя настройкам, все каналы работают нормально, но если взять GPIO 9, то происходит зависание процессора (node mcu 3v)
если я использую GPIO 1 то все работает. 
не пробовал использовать таймер с 12 каналами долгое время, только настраиваю плату.  подскажите почему зависает GPIO 9 и можно ли использовать GPIO 1 - никакой синхронизации или прошивки происходить не будет.

**Comment by Araris** [comment]
И Вам здравствуйте.
В рекомендациях по использованию GPIO я руководствовался вот этим :

![ESP8266_PINs_using_2](https://github.com/Araris/VersatileTimer/assets/2635051/87321935-1af7-41e0-9175-18870fdf22f2)

Советую забить в поисковик что-то типа "esp8266 gpio9 using" и получить исчерпывающую информацию, почему нельзя использовать GPIO9.

**Comment by Araris** [comment]
https://elchupanibrei.livejournal.com/65731.html

**Comment by Araris** [comment]
Полезное : 
https://elchupanibrei.livejournal.com/65731.html

**Comment by bdu1977** [comment]
спасибо за ответ. для меня это темный лес. но в любом случае прочитаю, попытаюсь понять. хотя для меня главное это задействовать 12 каналов для таймера. если получиться, то на основе вашего проекта я сделаю 12 независимых радиомодулей для управления гирляндами на Новый Год

**Comment by bdu1977** [comment]
собрал все на макетной плате. появилась еще одна проблема. если я включаю схему и к GPIO 4 подключена нагрузка (реле), то у меня процессор не запускается, он сразу начинает трещать и пищать. перезагрузка не помогает. а если отключить плату и отключить нагрузку от GPIO 4 затем включить питание и дождаться пока процессор загрузится (в браузере обновится меню управления) то в этом режиме можно к GPIO 4 подключать нагрузку и все будет работать, но до тех пор пока не отключится питание. не подскажите в чем проблема? у меня 11 каналов рабочих, и нужен еще один.

**Comment by Araris** [comment]
Подсказка в таблице, которая вставлена картинкой выше : boot fails if pulled LOW.
